version: 2

models:
  - name: stg_taxi_trips_yellow
    description: "Cleaned yellow trips: renamed & typed columns."
    columns:
      - name: pickup_ts
        tests: [not_null]
      - name: dropoff_ts
        tests: [not_null]
      - name: total_amount
        tests: [not_null]

  - name: stg_taxi_zones
    description: "Normalized zone lookup."
    columns:
      - name: zone_id
        tests: [not_null, unique]