services:
  spark-driver:
    build:
      context: ..
      dockerfile: docker/spark.Dockerfile
    image: spark-local:latest
    container_name: spark-driver
    volumes:
      - ../:/app
    working_dir: /app
    command: tail -f /dev/null
